"""
Renders a CMS template file with content_json injected via Jinja2.

Supports full Jinja2 syntax in template files:
  {{ hero.heading_line_1 }}          — simple value
  {{ destinations.0.country }}       — numeric string key in dict
  {% for step in journey.steps %}    — loops
  {% if item.value %}                — conditionals
  {{ loop.index }}                   — Jinja2 loop variables
"""
import json
import os

import frappe
from jinja2.sandbox import SandboxedEnvironment


class _CMSEnv(SandboxedEnvironment):
    """Jinja2 env with two fixes for content JSON dicts:

    1. Dict key access beats Python built-in attribute access, so keys like
       "items", "keys", "values" aren't shadowed by dict methods.
    2. Numeric string keys (e.g. "0", "1") are accessible via dot notation
       (destinations.0) even though Jinja2 passes the integer 0 as attribute.
    """
    def getattr(self, obj, attribute):
        if isinstance(obj, dict):
            if attribute in obj:
                return obj[attribute]
            str_attr = str(attribute)
            if str_attr in obj:
                return obj[str_attr]
        return super().getattr(obj, attribute)

    def getitem(self, obj, argument):
        if isinstance(obj, dict):
            if argument in obj:
                return obj[argument]
            str_arg = str(argument)
            if str_arg in obj:
                return obj[str_arg]
        return super().getitem(obj, argument)


_env = _CMSEnv(keep_trailing_newline=True)


def render_preview(doctype: str, doc_name: str) -> str:
    """Load the doc's template file and render it with content_json."""
    doc = frappe.get_doc(doctype, doc_name)
    content = {}
    if doc.content_json:
        try:
            content = json.loads(doc.content_json)
        except json.JSONDecodeError:
            frappe.throw("content_json on this document is not valid JSON.")
    return render_preview_with_content(doctype, doc_name, content)


def render_preview_with_content(doctype: str, doc_name: str, content: dict) -> str:
    """Render using the doc's template but with a supplied content dict (e.g. translated_json)."""
    doc = frappe.get_doc(doctype, doc_name)

    if not doc.template:
        frappe.throw("No template selected on this document.")

    template_doc = frappe.get_doc("CMS Template", doc.template)

    if not template_doc.template_file:
        frappe.throw(
            f"Template '{doc.template}' has no template file uploaded. "
            "Upload an HTML file in CMS Template → Template File."
        )

    template_html = _read_template_file(template_doc.template_file)
    return _inject(template_html, content)


def _read_template_file(file_url: str) -> str:
    """Resolve Frappe file URL or public https:// URL and return HTML contents."""

    # S3 / external URL (generated by agent service)
    if file_url.startswith("https://") or file_url.startswith("http://"):
        import requests
        resp = requests.get(file_url, timeout=30)
        resp.raise_for_status()
        return resp.text

    # Local Frappe file
    site_path = frappe.utils.get_site_path()

    if file_url.startswith("/private/files/"):
        rel = file_url.lstrip("/")
    elif file_url.startswith("/files/"):
        rel = "public/" + file_url.lstrip("/")
    else:
        rel = "public/files/" + os.path.basename(file_url)

    full_path = os.path.join(site_path, rel)

    if not os.path.exists(full_path):
        frappe.throw(f"Template file not found on disk: {file_url}")

    with open(full_path, "r", encoding="utf-8") as f:
        return f.read()


def _inject(template: str, content: dict) -> str:
    """Render Jinja2 template with content dict as context."""
    try:
        return _env.from_string(template).render(**content)
    except Exception as e:
        frappe.throw(f"Template rendering error: {e}")
